### ISSUE TITLE
[Bug]Webhooks报错

### ISSUE THREAD

**Issue by yuyi919** [ElpsyCN/el-bot-js#7]
```
[webhook](undefined): {"ref":"refs/heads/master","before"...
[WARNING] Bye, Master!
_http_outgoing.js:485
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.writeHead (_http_server.js:264:21)
    at hasError (/home/ubuntu/bot/node_modules/github-webhook-handler/github-webhook-handler.js:83:11)
    at BufferListStream._callback (/home/ubuntu/bot/node_modules/github-webhook-handler/github-webhook-handler.js:120:16)
    at BufferListStream.end (/home/ubuntu/bot/node_modules/github-webhook-handler/node_modules/bl/bl.js:65:10)
    at onend (_stream_readable.js:687:10)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
不太清楚是不是github-webhook-handler库的问题

另外报错后bot服务挂了，mirai还在运行中，也许需要优化错误处理？

**Comment by YunYouJun** [comment]
上次 webhook 集成时后有点问题，现在正在紧急抢修。（

**Comment by YunYouJun** [comment]
紧急修复完了，更新至 `el-bot@0.5.11` 以上。
